### ISSUE TITLE
Initial thoughts on the code

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-kubernetes-plugin#2]
- Generally speaking I'd probably [write the plugin in Java](https://guides.gradle.org/designing-gradle-plugins/#prefer_using_a_statically_typed_language_to_implement_a_plugin) these days for better forward and backward compatibility.
- `build.gradle` should use the [Java Plugin Development Plugin](https://guides.gradle.org/implementing-gradle-plugins/#plugin-development-plugin). It already takes care of a bunch of boilerplate code.
- Why exactly is the [`slf4j-simple` dependency needed](https://github.com/bmuschko/gradle-kubernetes-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/kubernetes/plugin/GradleKubernetesPlugin.groovy#L88)? If it's need for `kubernetes-client` why is it not defined as transitive dependency?
- [Configuration blocks](https://github.com/bmuschko/gradle-kubernetes-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/kubernetes/plugin/domain/ConfigureAware.groovy#L74) should use [Actions instead of Closures](https://guides.gradle.org/implementing-gradle-plugins/#modeling_dsl_like_apis) to make the plugin compatible with the Kotlin DSL.
- I think the exposed extension should look more Gradle idiomatic. Forward the method calls of the Kubernetes client doesn't read well e.g. with `withMasterUrl(String)` should probably be `masterUrl = <String>`.
- It's awesome that you run the functional tests on Travis CI!

**Comment by cdancy** [comment]
@bmuschko thanks for the feedback! My responses inline:
> Generally speaking I'd probably write the plugin in Java these days for better forward and backward compatibility.
- If we do this, which I don't necessarily disagree with, we lose a lot of the ad-hoc magic that makes the plugin work (e.g. loading dependencies dynamically and when needed). I don't know if there is a good way to do `def` type of things in java but groovy makes working with unknown objects a breeze.
> Why exactly is the slf4j-simple dependency needed? If it's need for kubernetes-client why is it not defined as transitive dependency?
- Can't remember the exception off the top of my head but something was popping at runtime when it wasn't included.
> Configuration blocks should use Actions instead of Closures to make the plugin compatible with the Kotlin DSL.
- That should be easy enough to do.
> I think the exposed extension should look more Gradle idiomatic. Forward the method calls of the Kubernetes client doesn't read well e.g. with withMasterUrl(String) should probably be masterUrl = <String>.
- on the config object you noted you can do things like `masterUrl = String` or `masterUrl <some-string>` I just used the `with` pattern for that specific case as I tend to like it.
> It's awesome that you run the functional tests on Travis CI!
- Took 2 days of banging my head trying to get this working only to stumble upon some snippets online, that I massaged for our use-case, and knocked out in about 10 minutes.
