### ISSUE TITLE
Bintray/JCenter expose plugin to world!!!

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-kubernetes-plugin#3]
@bmuschko just knocked out the first `0.0.1` release and it's now published to Bintray. Can you put in the request to expose it publicly? Believe it's on the project page and just a button or form you have to fill out. Usually takes a couple days for them to get back.

**Comment by bmuschko** [comment]
done

**Comment by cdancy** [comment]
@bmuschko thanks!

**Comment by bmuschko** [comment]
Heads up: The request has been approved.

**Comment by cdancy** [comment]
@bmuschko awesome! Really happy with the overall design. The code is clean, concise, and well documented. I know you have some gripes with it not being java but we couldn't easily do half the things we're doing without using groovy.

In either event the general structure is now in place and plan on adding more and more tasks over the next few weeks. Hopefully I can try to get the wider community involved and see if things make sense and how devs might use it.
